def A53_decoder(residue,quotient):
    s_re=str(residue)
    msg={
        "1": lambda quotient: quotient,
        "2": lambda quotient: quotient,
        "4": lambda quotient: quotient,
        "8": lambda quotient: quotient,
        "16": lambda quotient: quotient,
        "32": lambda quotient: quotient,
        "11": lambda quotient: quotient-1,
        "22": lambda quotient: quotient-2,
        "44": lambda quotient: quotient-4,
        "35": lambda quotient: quotient-9,
        "17": lambda quotient: quotient-19,
        "34": lambda quotient: quotient-38,
        "15": lambda quotient: quotient-77,
        "30": lambda quotient: quotient-154,
        "7": lambda quotient: quotient-309,
        "14": lambda quotient: quotient-618,
        "28": lambda quotient: quotient-1236,
        "3": lambda quotient: quotient-2473,
        "6": lambda quotient: quotient-4946,
        "12": lambda quotient: quotient-9892,
        "24": lambda quotient: quotient-19784,
        "48": lambda quotient: quotient-39568,
        "43": lambda quotient: quotient-79137,
        "33": lambda quotient: quotient-158275,
        "13": lambda quotient: quotient-316551,
        "52": lambda quotient: quotient+1,
        "51": lambda quotient: quotient+1,
        "49": lambda quotient: quotient+1,
        "45": lambda quotient: quotient+1,
        "37": lambda quotient: quotient+1,
        "21": lambda quotient: quotient+1,
        "42": lambda quotient: quotient+2,
        "31": lambda quotient: quotient+3,
        "9": lambda quotient: quotient+5,
        "18": lambda quotient: quotient+10,
        "36": lambda quotient: quotient+20,
        "19": lambda quotient: quotient+39,
        "38": lambda quotient: quotient+78,
        "23": lambda quotient: quotient+155,
        "46": lambda quotient: quotient+310,
        "39": lambda quotient: quotient+619,
        "25": lambda quotient: quotient+1237,
        "50": lambda quotient: quotient+2474,
        "47": lambda quotient: quotient+4947,
        "41": lambda quotient: quotient+9893,
        "29": lambda quotient: quotient+19785,
        "5": lambda quotient: quotient+39569,
        "10": lambda quotient: quotient+79138,
        "20": lambda quotient: quotient+158276,
        "40": lambda quotient: quotient+316552,
    }[s_re](quotient)
    msg
    return int(msg)
        